image: Visual Studio 2017

environment:
  matrix:
  - solution_path: Homework_2\Homework_2.sln
  - solution_path: Homework_3\ListLib\ListLib.sln
  - solution_path: Homework_3\StackCalculator\StackCalculator.sln
  - solution_path: Homework_4\TreeCalculator\TreeCalculator.sln
  - solution_path: Homework_4\UniqueList\UniqueList.sln

before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%